services:
  prjhealthcaresystem:
    image: prjhealthcaresystem
    build:
      context: .   # <--- Change this from ./prjHealthCareSystem to just a dot (.)
      dockerfile: prjHealthCareSystem/Dockerfile # <--- Point to the file here
    ports:
      - 8081:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Development